const streetNames = [
  'Corso Italia',
  'Piazza del Popolo',
  'Viale Dante Alighieri',
  'Via Garibaldi',
  'Via Cesare Battisti',
  'Via Emilia',
  'Via Circonvallazione',
  'Piazza della Libertà',
  'Via dei Mille',
  'Via Don Minzoni',
  'Viale della Rimembranza',
  'Via delle Terme',
  'Via Benedetto Croce',
  'Piazza Gramsci',
  'Viale Baccarini',
  'Via Malatestiana',
  'Via Aldo Moro',
  'Piazza della Resistenza',
  'Via del Popolo',
  'Corso Giuseppe Verdi',
  'Viale Europa',
  'Via delle Querce',
  'Piazza delle Fontane',
  'Via delle Palme',
  'Viale della Pace',
  'Via dei Vespri',
  'Piazza delle Rose',
  'Viale dello Sport',
  'Via del Podere',
  'Viale della Repubblica',
  'Piazza Marconi',
  'Via Leopardi',
  'Corso Kennedy',
  'Via XX Settembre',
  'Via dei Colli',
  'Via delle Azalee',
  'Viale dei Gelsomini',
  'Viale dei Fiori',
  'Via dei Cipressi',
  'Via della Vittoria',
  'Via delle Orchidee',
  'Via dei Cedri',
  'Viale delle Camelie',
  'Corso della Pace',
  'Viale delle Margherite',
  'Via dei Girasoli',
  'Piazza Garibaldi',
  'Via dei Papaveri',
  'Corso della Repubblica',
  'Via della Libertà',
  'Viale degli Oleandri',
  'Via dei Gerani',
  'Piazza della Vittoria',
  'Viale dei Cipressi',
  'Via delle Magnolie',
  'Corso delle Rose',
  'Via dei Tulipani',
  'Viale delle Orchidee',
  'Piazza del Mercato',
  'Via delle Camelie',
  'Viale delle Azalee',
  'Piazza dei Cedri',
  'Corso Europa',
  'Via delle Margherite',
  'Viale dei Girasoli',
  'Piazza Italia',
  'Corso dei Platani',
  'Via degli Oleandri',
  'Viale delle Ginestre',
  'Piazza Mazzini',
  'Viale delle Palme',
  'Piazza dei Fiori',
  'Corso Vittorio Emanuele',
  'Via della Repubblica',
  'Viale XX Settembre',
  'Piazza Giuseppe Verdi',
  'Corso della Vittoria',
  'Via delle Rose',
  'Viale delle Rose',
  'Piazza Santa Maria',
  'Corso Cavour',
  'Via dei Tigli',
  'Viale delle Magnolie',
  'Piazza Leopardi',
  'Corso Mazzini',
  'Via delle Mimose',
  'Viale dei Pini',
  'Piazza Risorgimento',
  'Corso Giuseppe Mazzini',
  'Via degli Ulivi',
  'Viale dei Tigli',
  'Piazza Manzoni',
  'Corso Matteotti',
  'Via Carducci',
  'Piazza Cavour',
  'Corso Repubblica',
  'Via Matteotti',
  'Viale della Libertà',
  'Piazza Maggiore',
  'Via Roma',
];
  
  module.exports = streetNames;